const Icons = {
  home: require("../assets/icons/home.png"),
  map: require("../assets/icons/map.png"),
  list: require("../assets/icons/list.png"),
  bell: require("../assets/icons/bell.png"),
  user: require("../assets/icons/user.png"),
  signout: require("../assets/icons/log-out.png"),
  search: require("../assets/icons/search.png"),
  settings: require("../assets/icons/settings.png"),
  sideMenu: require("../assets/icons/side-menu-icon.png"),
  calendar: require("../assets/icons/calendar.png"),
  tracker: require("../assets/icons/tracker.png"),
  trackerBlack: require("../assets/icons/tracker-black.png"),
  parking: require("../assets/icons/parking.png"),
  parkings: require("../assets/icons/parkings.png"),
  parkingsGray: require("../assets/icons/parkings-gray.png"),
  fence: require("../assets/icons/fence.png"),
  fenceGray: require("../assets/icons/fence-gray.png"),
  subscription: require("../assets/icons/subscription.png"),
  alert: require("../assets/icons/alert.png"),
  devices: require("../assets/icons/devices.png"),
  speedometer: require("../assets/icons/speedometer.png"),
  distance: require("../assets/icons/distance.png"),
  detailed: require("../assets/icons/detailed.png"),
  card: require("../assets/icons/card.png"),
  parkingGreen: require("../assets/icons/parking-green.png"),
  stoppage: require("../assets/icons/stoppage.png"),
  immobilize: require("../assets/icons/stoppage.png"),
  engine: require("../assets/icons/engine.png"),
  stopHand: require("../assets/icons/stop-hand.png"),
  fuel1: require("../assets/icons/fuel-1.png"),
  fuel2: require("../assets/icons/fuel-2.png"),
  controls: require("../assets/icons/controls.png"),
  moving: require("../assets/icons/moving.gif"),
  idle: require("../assets/icons/idle.png"),
  route: require("../assets/icons/route.png"),
  plus: require("../assets/icons/plus.png"),
  shareLocation: require("../assets/icons/share-location.png"),
  driver: require("../assets/icons/driver.png"),
  routeTrack: require("../assets/icons/route-track.png"),
  flag: require("../assets/icons/flag.png"),
  ignitionOff: require("../assets/icons/ignition.png"),
  ingnitionOn: require("../assets/icons/ignition.png"),
  pluggedOut: require("../assets/icons/ignition.png"), 
  ic_radiobox_blank: require("../assets/icons/radiobox-blank.png"),
  ic_radiobox_marked: require("../assets/icons/radiobox-marked.png"),
  marker: require("../assets/icons/Marker.png"),
  avatar: require("../assets/icons/avatar.jpg"),

  battery_green: require("../assets/ic-notification/battery-green.png"), 
  battery_red: require("../assets/ic-notification/battery-red.png"), 
  geofence_arrived_in: require("../assets/ic-notification/geofence-arrived-in.png"), 
  geofence_left: require("../assets/ic-notification/geofence-left.png"), 
  ignition: require("../assets/ic-notification/ignition.png"), 
  ignition_off: require("../assets/ic-notification/ignition-off.png"), 
  immobilizer_cut: require("../assets/ic-notification/immobilizer-cut.png"), 
  immobilizer_restore: require("../assets/ic-notification/immobilizer-restore.png"), 
  maintenance: require("../assets/ic-notification/maintenance.png"), 
  no_gps: require("../assets/ic-notification/no-gps.png"), 
  order_placed: require("../assets/ic-notification/order-placed.png"), 
  overspeed: require("../assets/ic-notification/overspeed.png"), 
  parking_mode: require("../assets/ic-notification/parking-mode.png"), 
  unplugged: require("../assets/ic-notification/unplugged.png"),  
};

export const Images = {
  bgImage: require('../assets/images/bg.png'),
  loginLogo: require('../assets/images/login-logo.png'),
  sideMenuLogo: require('../assets/images/side-menu-logo.png'),
  mainLogo: require("../assets/images/logo1024-1024_3.png"),
  mainLoginLogo: require("../assets/images/logo1024-1024.png"),
  drawerLogo: require("../assets/images/mainIcoon2.png"),
  truck: require("../assets/images/truck.png"), 
};

export default Icons;
