export default (uriConfig = {
  apiUrl: "http://api.trackugo.in/",
  // apiUrl: "http://api-staging.trackugo.in/",
  geocode: "https://maps.googleapis.com/maps/api/geocode/json",
  uri: {
    CONFIGURATIONS: "configurations",
    USERNAME_AVAILABLE: "username-available",
    SIGNIN: "signin",
    SIGNUP: "signup",
    SIGNUP_VERIFY: "signup/verify",
    RESEND_OTP: "resend-otp",
    SIGNOUT: "user/signout",
    TOKEN_REVIVE: "token/revive",
    FORGOT_PASSWORD: "forgot-password",
    RESET_PASSWORD: "reset-password",
    USER_PROFILE: "user/profile",
    CHANGE_PASSWORD: "user/change-password",
    NOTIFICATIONS: "user/notifications",
    CHATUSERS: "chat/user",
    CHATROOM: "chat/user/message",
    USER_CART: "user/cart",
    USER_LOCATION: "user/location",
    USER_EVENT: "user/userevent",

    DEVICES: "device/list",
    DEVICES_ALL: "device/all",
    DEVICES_NEARBY: "device/nearby",
    DEVICE_DETAILS: "device/details",
    IMMOBILIZE_DEVICE: "device/immobilize",
    DEVICE_LATEST_TRIP: "device/latest-trip",
    DEVICE_PLAYBACK: "device/playback",
    DEVICE_ACTIVATE: "device/activate",
    DEVICE_FUEL_SETTINGS: "device/fuel-settings",

    ORDERS: "order/list",
    ORDER_DETAILS: "order",
    ORDER_NEW: "order/new",
    ORDER_PAYMENT_RESPONSE: "order/payment-response",
    ORDER_PAYMENT_VERIFY: "order/payment-verify",

    PAYMENTS: "payment/list",
    PAYMENT_DETAILS: "payment/details", 

    ICONS: "device/icons",
    DEVICE_DRIVER: "device/driver",
    SUBSCRIPTIONS: "device/subscriptions",
    DEVICE_MODELS: "device/models",
    DEVICE_MODEL_DETAILS: "device/model",
    VEHICLE_TYPES: "device/vehicle-types",

    PACKAGES: "package/list",
    PACKAGE_VALIDATE: "package/validate",
    PACKAGE_PURCHASE: "package/purchase",
    PACKAGE_PAYMENT_RESPONSE: "package/payment-response",
    PACKAGE_PAYMENT_VERIFY: "package/payment-verify", 

    PARKING_LOCATIONS: "parking-location/list",
    PARKING_LOCATION_DETAILS: "parking-location/details",
    PARKING_LOCATION_SAVE: "parking-location/save",
    PARKING_LOCATION_DELETE: "parking-location/delete",

    GEO_FENCING_LIST_SINGLE: "geo-fence/list?type=",
    GEO_FENCING: "geo-fence/list",
    GEO_FENCE_DETAILS: "geo-fence/details",
    GEO_FENCE_SAVE: "geo-fence/save",
    GEO_FENCE_SAVE_ALL: "geo-fence/save-all",
    GEO_FENCE_DELETE: "geo-fence/delete",

    ALERT_DETAILS: "alert/details",
    ALERT_SAVE: "alert/save",

    REPORT_TRIP: "report/trip",
    REPORT_IDLE: "report/idle",
    REPORT_DETAILED: "report/detailed",
    REPORT_STOPPAGE: "report/stoppage",
    REPORT_DISTANCE: "report/distance",
    REPORT_CONSOLIDATED: "report/consolidated",

    SHARED_LOCATION: "user/shared-location",
    SHARED_LOCATIONS: "user/shared-locations",
    SHARED_LOCATION_SAVE: "user/shared-location/save",
    SHARED_LOCATION_EXPIRE: "user/shared-location/expire",

    CREATE_GROUP: "circle/create-group",
    DELETE_GROUP: "circle/delete-group",
    ADD_TO_GROUP: "circle/addToGroup",
    REMOVE_FROM_GROUP: "circle/removeFromGroup",
    GET_ALL_GROUP: "circle/getAllGroup",
    circle_updateGroup: "circle/updateGroup",
    geo_fence_save_group: "geo-fence/save-group", 
    circle_paymentresponse: "package/circle/paymentresponse",  

    // deepLinkUrlPrefix: "https://trackyou.page.link/code",
    // deepLinkName: "trackyou",
    deepLinkUrlPrefix: "https://trackyou.page.link",
    deepLinkName: "Circle",
    packageName: "com.trackyou",
  },
});